name: Publish 

on: 
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./VitalCareWeb.sln

      - name: Build
        run: dotnet build ./VitalCareWeb.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./VitalCareWeb.sln --configuration Release --no-build

        

        
        
        
    
